### ISSUE TITLE
Autosave should save complete document

### ISSUE THREAD

**Issue by janno42** [fsr-itse/1327#385]
When creating a document, only the text gets autosaved. Poll options, comment, title, start and end date, minute taker, guests, ... are not saved. They should be included in the autosave.

**Comment by Bartzi** [comment]
Won't fix this.

It is pretty difficult to implement such a behaviour, because of the following reasons:
- django is not designed to perform autosaves
- you'll need a shadow copy of the original document, with that you will need to make sure that this is always up to date and never leaks any changes to the orignal document, that means double bookkeeping
- furthermore it is nearly impossible to handle foreignkeys to the original document with the shadow copy, as you'll need to merge them together or s.th., but this behaviour is highly document dependent and hardly abstractable, rendering nearly everything we did obsolete
- it is not really possible to determine changes in the form on the website via javascript, that means we would need to send an auosave request every 10 seconds, even though nothing changed, this would put unecessary load on the server

This should provide some impressions, why we won't fix this ;)
