### ISSUE TITLE
Document creation for non-superusers

### ISSUE THREAD

**Issue by janno42** [fsr-itse/1327#388]
Currently users who are not superusers can not create documents (minutes, information pages, polls) if they only have the create permission for these objects, because the creation redirects to the edit view that checks the edit permission. General edit permissions per object type should not be granted, so we need a different solution here.
Creating a document could give an additional parameter to the edit view stating that no edit permission is needed. However, once saving the document, the user won't be able to access it again, so the user can't even grant own permissions. The last-mentioned is an issue for all documents besides minutes, because these are assigned to a group on creation. Perhaps we should assign initial permissions on creation also for the other document types?

**Comment by Nef10** [comment]
- [ ] while creating the edit permissions should not be checked (for all document types)
- [ ] do not show group form while editing (minutes)
- [ ] do only allow selection of one group (minutes)
- [ ] allow the selection of one group (polls and information documents)
- [ ] do not save group in database (minutes)
- [ ] set initial permissions (edit and view) for the selected group (all document types)
- [ ] remove overview site with minutes of more than one group
- [ ] minutes overview site has to check edit rights (instead of removed group field) to show the documents
- [ ] remove group name from minutes document site
